import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import FixAppBar from "../widgets/primary/appBar/FixAppBar";
import { Alert, Box, Snackbar, Toolbar } from "@mui/material";
import ReduxProviderWrapper from "./GlobalRedux/provider";
import { headers } from "next/headers";
import { MainAppBar } from "@/widgets/primary/appBar/MainAppBar";
import MainSideBar from "./partials/widgets/MainSideBar";
import FcmTokenComp from "./(Widgets)/(Handlers)/firebaseForeground";
import MyToast from "./partials/widgets/MyToast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mainWrapperStyle = {
  display: "flex",
  minHeight: "100vh",
  width: "100%",
}

const pageWrapperStyle = {
  display: "flex",
  flexGrow: 1,
  paddingBottom: "60px",
  flexDirection: "column",
  zIndex: 1,
  width: "100%",
  backgroundColor: "transparent",
}

export default function RootLayout({ children }) {
  const header = headers();
  const mUrl = header.get('x-url')

  const urls = [
    'login'
  ]


  const is = urls.find(url => mUrl.includes(url));

  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>

      <body className={inter.className} style={{minHeight: '100vh',backgroundRepeat: 'no-repeat', backgroundColor: '#fff ' , overflow: 'auto',  }}>
        <AppRouterCacheProvider>
          <ReduxProviderWrapper >
            <ThemeProvider theme={theme}>
              <FcmTokenComp />
              <MyToast />
              {children}
              {/* <div style={mainWrapperStyle}>
                <MainSideBar />

                <Box
                  className="page-wrapper"
                  sx={{}}
                  style={pageWrapperStyle}
                >
                  <MainAppBar />
                  {children}
                  
                </Box>


              </div> */}



            </ThemeProvider>
          </ReduxProviderWrapper>


        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
