import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import FixAppBar from "../widgets/primary/appBar/FixAppBar";
import { Toolbar } from "@mui/material";
import ReduxProviderWrapper from "./GlobalRedux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>

      <body className={inter.className} style={{ backgroundColor: '#fff', overflow: 'hidden' }}>
        <AppRouterCacheProvider>
          <ReduxProviderWrapper >
            <ThemeProvider theme={theme}>
              <FixAppBar />

              {children}
            </ThemeProvider>
          </ReduxProviderWrapper>


        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
